---

- name: Install Bacula Client package
  package:
    name: "{{ bacula_client_pkg }}"
  notify:
    - Restart Bacula Client service
  tags:
    - bacula_client_pkg

- name: Configure Bacula Client service
  template:
    src: bacula-fd.conf.j2
    dest: "{{ bacula_client_config_file_path }}"
  notify:
    - Restart Bacula Client service
  tags:
    - bacula_client_config

- name: Configure Bacula Client sysconfig
  template:
    src: bacula-fd.sysconfig.j2
    dest: "{{ bacula_client_sysconfig_file }}"
  notify:
    - Restart Bacula Client service
  when: ansible_os_family == "RedHat"
  tags:
    - bacula_client_config

- name: Make sure the Bacula Client service is enabled
  service:
    name: "{{ bacula_client_service }}"
    enabled: yes
  tags:
    - bacula_client_service

- name: Make sure the Bacula Client service is running
  service:
    name: "{{ bacula_client_service }}"
    state: started
  register: bacula_client_service_started
  tags:
    - bacula_client_service
